### ISSUE TITLE
"Web tool" link is broken

### ISSUE THREAD

**Issue by aparrish** [hylyh/bondage.js#51]
[This link](http://hayley.zone/bondage.js/) to the "web tool" is broken for me right now (leads to a GitHub Pages 404). (Though I ventured a guess that the content would also be available at [https://hylyh.github.io/bondage.js/](https://hylyh.github.io/bondage.js/), which appears to work fine...)

**Comment by manuq** [comment]
Is not broken right now.

**Comment by blurymind** [comment]
this issue  can be closed now
