### ISSUE TITLE
Ability to display variable values in text aka Hello, {$playername}

### ISSUE THREAD

**Issue by blurymind** [hylyh/bondage.js#59]
The yarn spinner guys are adding this, so I wonder if you would be open to add it to bondagejs as well :)

So we could say 
`I have {$applesCount} apples`
or
`My name is {$playerName}`

I can try to do a PR if this feature is welcome

**Comment by blurymind** [comment]
see yarnspinners documentation for reference
https://yarnspinner.dev/docs/syntax

**Comment by blurymind** [comment]
There is some other stuff too, if you look at https://yarnspinner.dev/docs/syntax

I believe it's completely lacking all Format functions that  yarnSpinner supports, example:
`You have {$apples} [plural {$apples} one="apple" other="apples"]`

**Comment by alforno** [comment]
That is called an inline expression. I'm working on implementing this in my fork.

**Comment by blurymind** [comment]
@alforno any progress on this?

**Comment by alforno** [comment]
I have not done any work on the format functions, but the issue I mention here is resolved in my fork. Last I check my previous pull request was not merged. I don't care if someone wants to take what I've done and make it work here, but I can't skip code revisions that led to this working.

**Comment by blurymind** [comment]
The format functions should be a separate pr anyways :) 

Sorry I haven't reviewed the other pr yet. I need to get back to my computer after the 9th and will give it a spin if @hylyh hasn't had a look yet.

Thank you for working on these and sorry for the slow reactions. The fixes and features are very much welcome and requested by a wider community of users outside of this tracker

**Comment by Chrissdroid** [comment]
If needed you can uses the javascript version of [Message Format](https://www.npmjs.com/package/messageformat) witch is used for YarnSpinner

**Comment by blurymind** [comment]
@Chrissdroid that is a fantastic suggestion. If we can maintain less code by using this library, it would leave us in a better place.
Would you be interested in creating a PR for this feature? It has been by far the most requested feature on this and other trackers using bondagejs

**Comment by blurymind** [comment]
There is now a PR for this, however its formater syntax is different from the yarnSpinner one. I raised a question at the library if we can make it work
https://github.com/messageformat/messageformat/issues/318

I am not sure if yarnSpinner actually does use MessageFormat. Its source code looks like they are doing it all manually
https://github.com/YarnSpinnerTool/YarnSpinner/commit/c6e375675a066b85e7a447dd093d1a10df39fd6b

although correct me if I'm wrong :) 

We still need to get the syntax be the same somehow. Otherwise we would be deviating from the yarnSpinner docs
