### ISSUE TITLE
Single option is working like a jump, not an option

### ISSUE THREAD

**Issue by alforno** [hylyh/bondage.js#64]
The syntax quick reference and the "controlling dialogue" sections of the YarnSpinner docs do not mention anywhere that a single option should be the equivalent of a jump. bondage js is skipping single options as if they are a jump. 

A jump has the format [[nodeName]]. Similar to an option, but only contains a link to another node, without providing a text choice for the player.

I think that currently, the code that does this is on runner.js line 149.

**Comment by blurymind** [comment]
Is that what yarnspinner has for spec?

**Comment by alforno** [comment]
Yes. The docs say [[description|nodeName]] for an option and [[nodeName]] for a jump. There is nothing stated in the docs that say a single option in a node is the same as a jump, or at least not that I could find. For now, I just changed that line of code in my local copy of the the js file, but wanted to let you know what I found. 
Regards.

**Comment by alforno** [comment]
Just in case you are looking for the info regarding jumps, it's at this link: https://yarnspinner.dev/docs/writing/controlling/

**Comment by blurymind** [comment]
yes indeed this was causing some confusion with gdevelop users as well. It
would be nice if someone does a pr to change the behaviour :)

**Comment by alforno** [comment]
I've got the jump working correctly on my fork of this project.

**Comment by alforno** [comment]
#65 implements the correct behavior for a single option and also adds Jump.

**Comment by alforno** [comment]
There are some downstream effects of my changes, one is that it invalidates the distinction "named option", since all options are named. An option without a name is called a Jump. It might take a little time to unravel this and the get tests passing again.

**Comment by alforno** [comment]
#66 The tests are now passing and the new pr submitted.

**Comment by blurymind** [comment]
thank you for this. Hope @hylyh gets some time and review this. Its very welcome
